import type { Metadata } from "next";
import { Nunito_Sans } from 'next/font/google'
import "./globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-nunito',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Buscador de Perfil no Github",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
       className={nunitoSans.variable}
      >
        {children}
      </body>
    </html>
  );
}
